### ISSUE TITLE
Deepl API free is not working

### ISSUE THREAD

**Issue by emvaized** [topce/auto-translate-json-library#6]
Errors in the developer console: 

<img width="845" alt="363846553-6b882128-9db5-4e35-b2a4-03b23800502c" src="https://github.com/user-attachments/assets/71940385-a372-472d-80e8-412881f62cf9">

Related issue: https://github.com/codegrue/auto-translate-json/issues/59

**Comment by topce** [comment]
@emvaized  thanks for reporting 
this should be fixed 
you can test it 

npm i
npm run build
node .\build\src\index.js --pivotTranslation=./tests/translations/en.json

.env
ATJ_IGNORE_PREFIX="@@"
ATJ_START_DELIMITER="{{"
ATJ_END_DELIMITER="}}"
ATJ_MODE=file
ATJ_SOURCE_LOCALE=en
ATJ_KEEP_TRANSLATIONS=keep
ATJ_KEEP_EXTRA_TRANSLATIONS=remove

ATJ_DEEPL_FREE_SECRET_KEY=your secret key
